/**
 * Arizen School — Design System v4
 * Soft Mint/Teal • Warm • Premium • Child-friendly
 *
 * Usage: import { ds, colors, gradients } from '@/lib/design-system'
 */

export const colors = {
  bg: 'rgb(var(--color-bg))',
  bgSoft: 'rgb(var(--color-bg-soft))',
  bgWarm: 'rgb(var(--color-bg-warm))',
  bgBlue: 'rgb(var(--color-bg-blue))',
  bgGreen: 'rgb(var(--color-bg-green))',
  bgPink: 'rgb(var(--color-bg-pink))',
  bgPurple: 'rgb(var(--color-bg-purple))',
  primary: 'rgb(var(--color-primary))',
  primaryLight: 'rgb(var(--color-primary-light))',
  primarySoft: 'rgb(var(--color-primary-soft))',
  primaryDark: 'rgb(var(--color-primary-dark))',
  accent: 'rgb(var(--color-accent))',
  accentLight: 'rgb(var(--color-accent-light))',
  accentSoft: 'rgb(var(--color-accent-soft))',
  accentDark: 'rgb(var(--color-accent-dark))',
  warm: 'rgb(var(--color-warm))',
  warmLight: 'rgb(var(--color-warm-light))',
  warmSoft: 'rgb(var(--color-warm-soft))',
  warmDark: 'rgb(var(--color-warm-dark))',
  text: 'rgb(var(--color-text))',
  textHeading: 'rgb(var(--color-text-heading))',
  textMuted: 'rgb(var(--color-text-muted))',
  textInverse: 'rgb(var(--color-text-inverse))',
  border: 'rgb(var(--color-border))',
  borderLight: 'rgb(var(--color-border-light))',
  success: 'rgb(var(--color-success))',
  danger: 'rgb(var(--color-danger))',
  warning: 'rgb(var(--color-warning))',
  info: 'rgb(var(--color-info))',
} as const;

export const gradients = {
  primary: `linear-gradient(135deg, ${colors.primary}, ${colors.primaryDark})`,
  primarySoft: `linear-gradient(135deg, ${colors.primarySoft}, white)`,
  accent: `linear-gradient(135deg, ${colors.accent}, ${colors.accentDark})`,
  warm: `linear-gradient(135deg, ${colors.warm}, ${colors.warmDark})`,
  hero: `linear-gradient(180deg, ${colors.bg} 0%, ${colors.bgBlue} 50%, ${colors.bgGreen} 100%)`,
  card: `linear-gradient(135deg, white, ${colors.bgSoft})`,
  cardHover: `linear-gradient(135deg, white, ${colors.primarySoft})`,
  sunset: `linear-gradient(135deg, ${colors.warmSoft}, ${colors.accentSoft})`,
  sky: `linear-gradient(135deg, ${colors.bgBlue}, ${colors.primarySoft})`,
  textPrimary: `linear-gradient(135deg, ${colors.primary}, ${colors.primaryDark})`,
  textAccent: `linear-gradient(135deg, ${colors.accent}, ${colors.warm})`,
  textWarm: `linear-gradient(135deg, ${colors.warm}, ${colors.accent})`,
} as const;

export const shadows = {
  xs: '0 1px 2px rgba(0,0,0,0.03)',
  sm: '0 1px 3px rgba(0,0,0,0.04), 0 2px 6px rgba(0,0,0,0.02)',
  md: '0 2px 8px rgba(0,0,0,0.05), 0 4px 16px rgba(0,0,0,0.03)',
  lg: '0 4px 16px rgba(0,0,0,0.06), 0 8px 32px rgba(0,0,0,0.03)',
  xl: '0 8px 32px rgba(0,0,0,0.08), 0 16px 64px rgba(0,0,0,0.04)',
  '2xl': '0 12px 48px rgba(0,0,0,0.1), 0 24px 80px rgba(0,0,0,0.05)',
  primary: '0 4px 20px rgba(13,148,136,0.18), 0 8px 32px rgba(13,148,136,0.08)',
  accent: '0 4px 20px rgba(251,113,133,0.18), 0 8px 32px rgba(251,113,133,0.08)',
  warm: '0 4px 20px rgba(245,158,11,0.18), 0 8px 32px rgba(245,158,11,0.08)',
  glow: '0 0 60px rgba(13,148,136,0.12)',
} as const;

export const ds = {
  // ── Layout ──
  page: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column' as const,
  },
  containerNarrow: {
    maxWidth: '720px',
    margin: '0 auto',
    padding: '0 1.5rem',
  },
  containerBase: {
    maxWidth: '1160px',
    margin: '0 auto',
    padding: '0 1.5rem',
  },

  // ── Cards ──
  card: {
    background: 'white',
    borderRadius: '1.5rem',
    border: `1px solid ${colors.borderLight}`,
    padding: '2rem',
    boxShadow: shadows.md,
    transition: 'box-shadow 0.3s ease, transform 0.3s ease',
  },
  cardInteractive: {
    background: 'white',
    borderRadius: '1.75rem',
    border: `1px solid ${colors.borderLight}`,
    padding: '2rem',
    boxShadow: shadows.md,
    transition: 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
    cursor: 'pointer' as const,
    textDecoration: 'none',
    display: 'block',
  },
  cardFlat: {
    background: 'white',
    borderRadius: '1.5rem',
    border: `1px solid ${colors.borderLight}`,
    padding: '2rem',
    boxShadow: shadows.sm,
  },
  cardGlass: {
    background: 'rgba(255,255,255,0.85)',
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    borderRadius: '1.5rem',
    border: `1px solid rgba(255,255,255,0.7)`,
    padding: '2rem',
    boxShadow: shadows.lg,
  },

  // ── Buttons ──
  btnPrimary: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    borderRadius: '1rem',
    padding: '0.875rem 2rem',
    fontSize: '0.9375rem',
    fontWeight: 700,
    color: 'white',
    background: gradients.primary,
    border: 'none',
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    boxShadow: shadows.primary,
    letterSpacing: '0.01em',
  } as React.CSSProperties,
  btnSecondary: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    borderRadius: '1rem',
    padding: '0.875rem 2rem',
    fontSize: '0.9375rem',
    fontWeight: 600,
    color: colors.primaryDark,
    background: colors.primarySoft,
    border: `1.5px solid ${colors.primaryLight}`,
    cursor: 'pointer',
    transition: 'all 0.25s ease',
  } as React.CSSProperties,
  btnAccent: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    borderRadius: '1rem',
    padding: '0.875rem 2rem',
    fontSize: '0.9375rem',
    fontWeight: 700,
    color: 'white',
    background: gradients.accent,
    border: 'none',
    cursor: 'pointer',
    transition: 'all 0.25s ease',
    boxShadow: shadows.accent,
  } as React.CSSProperties,
  btnWarm: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    borderRadius: '1rem',
    padding: '0.875rem 2rem',
    fontSize: '0.9375rem',
    fontWeight: 700,
    color: 'white',
    background: gradients.warm,
    border: 'none',
    cursor: 'pointer',
    transition: 'all 0.25s ease',
    boxShadow: shadows.warm,
  } as React.CSSProperties,
  btnGhost: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.35rem',
    borderRadius: '0.75rem',
    padding: '0.6rem 1.2rem',
    fontSize: '0.875rem',
    fontWeight: 600,
    color: colors.textMuted,
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  } as React.CSSProperties,
  btnOutline: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    borderRadius: '1rem',
    padding: '0.825rem 1.75rem',
    fontSize: '0.9375rem',
    fontWeight: 600,
    color: colors.primary,
    background: 'transparent',
    border: `2px solid ${colors.primary}`,
    cursor: 'pointer',
    transition: 'all 0.25s ease',
  } as React.CSSProperties,

  // ── Form ──
  input: {
    width: '100%',
    padding: '0.875rem 1.125rem',
    borderRadius: '1rem',
    fontSize: '0.9375rem',
    fontWeight: 500,
    color: colors.text,
    background: colors.bgSoft,
    border: `1.5px solid ${colors.border}`,
    transition: 'all 0.2s ease',
    outline: 'none',
    fontFamily: "'Nunito', system-ui, sans-serif",
  } as React.CSSProperties,
  inputFocus: {
    borderColor: colors.primary,
    boxShadow: `0 0 0 3px ${colors.primarySoft}`,
    background: 'white',
  },
  label: {
    display: 'block',
    fontSize: '0.8125rem',
    fontWeight: 700,
    marginBottom: '0.5rem',
    color: colors.text,
    letterSpacing: '0.02em',
    textTransform: 'uppercase' as const,
  } as React.CSSProperties,

  // ── Typography ──
  headingHero: {
    fontSize: 'clamp(2.25rem, 5.5vw, 3.5rem)',
    fontWeight: 900,
    letterSpacing: '-0.035em',
    lineHeight: 1.1,
    color: colors.textHeading,
  } as React.CSSProperties,
  headingLg: {
    fontSize: 'clamp(1.5rem, 3.5vw, 2rem)',
    fontWeight: 900,
    letterSpacing: '-0.03em',
    color: colors.textHeading,
    lineHeight: 1.15,
  } as React.CSSProperties,
  headingMd: {
    fontSize: '1.375rem',
    fontWeight: 800,
    color: colors.textHeading,
    letterSpacing: '-0.02em',
  } as React.CSSProperties,
  headingSm: {
    fontSize: '1.125rem',
    fontWeight: 800,
    color: colors.textHeading,
    letterSpacing: '-0.01em',
  } as React.CSSProperties,
  textBody: {
    fontSize: '0.9375rem',
    lineHeight: 1.7,
    color: colors.textMuted,
    fontWeight: 500,
  } as React.CSSProperties,
  textBodyLg: {
    fontSize: '1.0625rem',
    lineHeight: 1.75,
    color: colors.textMuted,
    fontWeight: 500,
  } as React.CSSProperties,
  textTagline: {
    fontSize: '0.75rem',
    fontWeight: 800,
    letterSpacing: '0.12em',
    textTransform: 'uppercase' as const,
    color: colors.primary,
  } as React.CSSProperties,

  // ── Alerts ──
  alertError: {
    display: 'flex',
    alignItems: 'flex-start' as const,
    gap: '0.65rem',
    background: 'rgba(239,68,68,0.06)',
    border: '1px solid rgba(239,68,68,0.15)',
    borderRadius: '1rem',
    padding: '0.875rem 1.125rem',
    marginBottom: '1rem',
  } as React.CSSProperties,
  alertSuccess: {
    display: 'flex',
    alignItems: 'flex-start' as const,
    gap: '0.65rem',
    background: 'rgba(34,197,94,0.06)',
    border: '1px solid rgba(34,197,94,0.15)',
    borderRadius: '1rem',
    padding: '0.875rem 1.125rem',
    marginBottom: '1rem',
  } as React.CSSProperties,

  // ── Logo ──
  logoMark: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '1rem',
    background: gradients.primary,
    color: 'white',
    boxShadow: shadows.primary,
  } as React.CSSProperties,

  // ── Gradient Text ──
  textGradient: {
    background: gradients.textPrimary,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
  } as React.CSSProperties,
  textGradientAccent: {
    background: gradients.textAccent,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
  } as React.CSSProperties,
  textGradientWarm: {
    background: gradients.textWarm,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
  } as React.CSSProperties,

  // ── Navbar ──
  nav: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    zIndex: 50,
    background: 'rgba(253,253,251,0.85)',
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    borderBottom: `1px solid ${colors.borderLight}`,
  } as React.CSSProperties,

  // ── Section ──
  section: {
    padding: '5rem 0',
  } as React.CSSProperties,

  // ── Decorative ──
  orb: (color: string, size: string = '20rem') => ({
    position: 'absolute' as const,
    width: size,
    height: size,
    borderRadius: '50%',
    filter: 'blur(80px)',
    background: color,
    opacity: 0.25,
    pointerEvents: 'none' as const,
  }),
} as const;
