#!/usr/bin/env node
/**
 * EMERGENCY FIX: Clear incorrectly generated journeys for non-English lessons.
 * These lessons had English reading/writing content incorrectly generated by the ELA script.
 * We clear the journeys and mark them as unavailable until proper regeneration.
 */
const fs = require('fs');
const path = require('path');
const envPath = path.join(__dirname, '..', '.env');
const envContent = fs.readFileSync(envPath, 'utf-8');
const envVars = {};
envContent.split('\n').forEach(line => {
  const t = line.trim();
  if (!t || t.startsWith('#')) return;
  const i = t.indexOf('=');
  if (i === -1) return;
  envVars[t.slice(0, i).trim()] = t.slice(i + 1).trim().replace(/^['"]|['"]$/g, '');
});
const { createClient } = require('@supabase/supabase-js');
const db = createClient(envVars.NEXT_PUBLIC_SUPABASE_URL, envVars.NEXT_PUBLIC_SUPABASE_ANON_KEY);

async function main() {
  console.log('=== EMERGENCY FIX: Clear incorrect non-English journeys ===\n');

  // Get ELA quest IDs
  const { data: elaTheme } = await db.from('Theme').select('id').eq('grade', 2).ilike('title', '%English Language Activities%').single();
  const { data: elaQuests } = await db.from('Quest').select('id').eq('themeId', elaTheme?.id);
  const elaQuestIds = elaQuests?.map(q => q.id) || [];

  // Get all lessons with the fix batch ID (or the ELA v3 batch)
  const { data: allLessons } = await db.from('Lesson').select('id, title, contentBlocks, questId').limit(2000);

  let cleared = 0, skipped = 0;

  for (const lesson of allLessons || []) {
    let meta = {};
    try { meta = JSON.parse(lesson.contentBlocks || '{}'); } catch(e) {}

    const batchId = meta.aiMetadata?.batchId || '';
    // Clear lessons from either the ELA batch or the fix batch that are NOT ELA
    const isIncorrectBatch = (batchId.includes('g2-ela-v3') || batchId.includes('g2-fix-non-ela')) && !elaQuestIds.includes(lesson.questId);
    
    if (!isIncorrectBatch) continue;

    // Clear journeys and mark unavailable
    const cleanedMeta = { ...meta };
    cleanedMeta.studentJourneyDraft = [];
    cleanedMeta.studentJourney = [];
    cleanedMeta.isAvailable = false;
    cleanedMeta.aiMetadata = {
      ...(cleanedMeta.aiMetadata || {}),
      cleared: true,
      clearedAt: new Date().toISOString(),
      note: 'Cleared incorrect English content. Needs subject-specific regeneration.',
    };

    const { error } = await db.from('Lesson')
      .update({ contentBlocks: JSON.stringify(cleanedMeta) })
      .eq('id', lesson.id);

    if (error) {
      console.log('ERROR:', lesson.title, error.message);
    } else {
      cleared++;
    }
  }

  console.log(`Cleared: ${cleared} lessons`);
  console.log('These lessons are now unavailable and need subject-specific regeneration.');
}

main().catch(e => console.error(e));
