#!/usr/bin/env node
/**
 * Revert non-ELA lessons that were incorrectly regenerated by the ELA script.
 * Restores the previous studentJourney from before the v3 batch.
 */
const fs = require('fs');
const path = require('path');
const envPath = path.join(__dirname, '..', '.env');
const envContent = fs.readFileSync(envPath, 'utf-8');
const envVars = {};
envContent.split('\n').forEach(line => {
  const t = line.trim();
  if (!t || t.startsWith('#')) return;
  const i = t.indexOf('=');
  if (i === -1) return;
  envVars[t.slice(0, i).trim()] = t.slice(i + 1).trim().replace(/^['"]|['"]$/g, '');
});
const { createClient } = require('@supabase/supabase-js');
const db = createClient(envVars.NEXT_PUBLIC_SUPABASE_URL, envVars.NEXT_PUBLIC_SUPABASE_ANON_KEY);

async function main() {
  console.log('=== Reverting non-ELA lessons incorrectly regenerated ===\n');

  // Get ELA quest IDs
  const { data: elaTheme } = await db.from('Theme').select('id').eq('grade', 2).ilike('title', '%English Language Activities%').single();
  const { data: elaQuests } = await db.from('Quest').select('id').eq('themeId', elaTheme?.id);
  const elaQuestIds = elaQuests?.map(q => q.id) || [];

  // Get all lessons with v3 batch that are NOT ELA
  const { data: allLessons } = await db.from('Lesson').select('id, title, contentBlocks, questId').limit(2000);

  let reverted = 0, skipped = 0;

  for (const lesson of allLessons || []) {
    let meta = {};
    try { meta = JSON.parse(lesson.contentBlocks || '{}'); } catch(e) {}

    const batchId = meta.aiMetadata?.batchId || '';
    if (!batchId.includes('g2-ela-v3')) continue;
    if (elaQuestIds.includes(lesson.questId)) continue; // Skip actual ELA lessons

    // Revert: remove the v3 journey, restore previous state
    // The old journey was stored in studentJourney before we overwrote it
    // Since we set both studentJourney and studentJourneyDraft to the new journey,
    // we need to clear both and restore from backup
    // Unfortunately we didn't backup the old journey. But the old journey was
    // the generic template from v2, which is still in the database for other lessons.
    
    // Best approach: clear the v3 journey and set status to needs regeneration
    const cleanedMeta = { ...meta };
    cleanedMeta.studentJourneyDraft = [];
    cleanedMeta.studentJourney = [];
    cleanedMeta.aiMetadata = {
      ...(cleanedMeta.aiMetadata || {}),
      reverted: true,
      revertedAt: new Date().toISOString(),
      note: 'Reverted — incorrectly regenerated by ELA script',
    };

    const { error } = await db.from('Lesson')
      .update({ contentBlocks: JSON.stringify(cleanedMeta) })
      .eq('id', lesson.id);

    if (error) {
      console.log('  ERROR:', lesson.title, error.message);
    } else {
      reverted++;
    }
  }

  console.log(`\\nReverted: ${reverted} lessons`);
  console.log('These lessons now have empty journeys and need to be regenerated by their subject-specific generators.');
}

main().catch(e => console.error(e));
